export type FoxState =
  | "sleep"
  | "sniff"
  | "dig"
  | "run"
  | "jump"
  | "caught"
  | "error"
  | "sad"
  | "swim";

export type RGB = readonly [number, number, number];

export interface FoxAnimation {
  label: string;
  intervalMs: number;
  frameDurationsMs?: number[];
  holdLastFrame?: boolean;
  once?: { durationMs: number; then: FoxState };
  grids: string[][];
}

export const FOX_WIDTH = 24;
export const FOX_HEIGHT = 20;

export const PALETTE: Record<string, RGB> = {
  N: [44, 23, 38],
  O: [255, 157, 14],
  D: [238, 106, 14],
  Y: [255, 199, 27],
  W: [255, 255, 255],
  S: [199, 207, 222],
  G: [78, 78, 78],
  B: [0, 0, 0],
  E: [74, 33, 35],
  F: [83, 40, 41],
  P: [255, 158, 147],
  Q: [104, 104, 104],
  H: [126, 126, 126],
  R: [238, 45, 62],
  C: [70, 174, 228],
};

const sprite = (source: TemplateStringsArray): string[] =>
  source.raw[0]
    .trim()
    .split("\n")
    .map((row) => row.trim().replace(/\.+$/, "").padEnd(FOX_WIDTH, "."));

const sideFrames = [
  sprite`
    ........................
    ........................
    ........................
    ........................
    ........................
    ...NNN.....NNNN.........
    ...NGGN...NGGGN.........
    ....NGDNNNDGWN..........
    ....NOOOOOOWSN..........
    .....FBYOBOON...........
    .....FBYOBOON...........
    ....NBYYYPWOWNNNN.......
    ....NSSSWWFWWOODDNN.....
    .....NNNFFWWOOOODDON....
    ......QNSSSWOOOODFDSN...
    .....QNSSWWOOOOOOFSSN...
    ....QQQNGFWGNNOOGNNNQQ..
    ....QQQNENGENQNGENQQQQ..
    .....QQQQNENQQNENQQQQ...
    ......QQQQQQQQQQQQQQ....
  `,
  sprite`
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ...NNN.....NNNN.........
    ...NGGN...NGGGN.........
    ....NGDNNNDGWN..........
    ....NOOOOOOWSN..........
    .....FBYOBOON...........
    .....FBYOBOON...........
    ....NBYYYPWOWNNNN.......
    ....NSSSWWFWWOODDNNN....
    .....NNNFFWWOOOODDOSN...
    .....QQNSSSWOOOODFDSSN..
    ....QQNGSSWOOOOOONNSNN..
    ....QQNENNGENNGGENENQQ..
    .....QQQQNENQQNENQQQQ...
    ......QQQQQQQQQQQQQQ....
  `,
  sprite`
    ........................
    ........................
    ........................
    ........................
    ........................
    ...NNN.....NNNN.........
    ...NGGN...NGGGN.........
    ....NGDNNNDGWN..........
    ....NOOOOOOWSN..........
    .....FBYOBOON...........
    .....FBYOBOON...........
    ....NBYYYPWOWNNNN.......
    ....NSSSWWFWWOODDNN.....
    .....NNNFFWWOOOODDON....
    ......QNSSSWOOOODFDSN...
    .....QNSSWWOOOOOOFSSN...
    ....QQQNGFWGNNOOGNNNQQ..
    ....QQQNENGENQNGENQQQQ..
    .....QQQQNENQQNENQQQQ...
    ......QQQQQQQQQQQQQQ....
  `,
  sprite`
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ...NNN.....NNNN.........
    ...NGGN...NGGGN.........
    ....NGDNNNDGWN..........
    ....NOOOOOOWSN..........
    .....FBYOBOON...........
    .....FBYOBOON...........
    ....NBYYYPWOWNNNN.......
    ....NSSSWWFWWOODDNNN....
    .....NNNFFWWOOOODDOSN...
    .....QQNSSSWOOOODFDSSN..
    ....QQQNSGOOOOOOGNNSNN..
    ....QQQNGENNNNNNGENNQQ..
    .....QQNENQQQQQQNENQQ...
    ......QQQQQQQQQQQQQQ....
  `,
];

const frontBounceFrames = [
  sprite`
    ........................
    ...........N............
    ..........NWN...........
    .........NWWSN..........
    ........NNOOONN.........
    .......NDOOYOODN........
    .....NNNNDOYODNNNN......
    .....NGGGNDODNGGGN......
    ......NWGDNNNDGWN.......
    ......NWOOOOOOOWN.......
    .......NOOOOOOON........
    .......NOBOYOBON........
    ......NWWBOYOBWWN.......
    .......NNPWBWPNN........
    ......NWSNNNNNSWN.......
    .....HHNOSSSSSONHH......
    .....HHNOOWWWOONHH......
    .....HHNGENNNEGNHH......
    ......HNENHHHNENH.......
    ........HHHHHHH.........
  `,
  sprite`
    ........................
    ........................
    ............NN..........
    ...........NSWN.........
    ..........NSWWWNN.......
    ........NNOOONNWN.......
    .......NDOOYOODN........
    .....NNNNDOYODNNNN......
    .....NGGGNDODNGGGN......
    ......NWGDNNNDGWN.......
    ......NWOOOOOOOWN.......
    .......NOOOOOOON........
    .......NOBOYOBON........
    ......NWWBOYOBWWN.......
    ......HNNPWBWPNNH.......
    .....HNWSNNNNNSWNH......
    .....HHNOSSSSSONHH......
    .....HHNENNNNEGNHH......
    ......HHHHHHHNENH.......
    ........HHHHHHH.........
  `,
  sprite`
    ........................
    ...........N............
    ..........NWN...........
    .........NWWSN..........
    ........NNOOONN.........
    .......NDOOYOODN........
    .....NNNNDOYODNNNN......
    .....NGGGNDODNGGGN......
    ......NWGDNNNDGWN.......
    ......NWOOOOOOOWN.......
    .......NOOOOOOON........
    .......NOBOYOBON........
    ......NWWBOYOBWWN.......
    .......NNPWBWPNN........
    ......NWSNNNNNSWN.......
    .....HHNOSSSSSONHH......
    .....HHNOOWWWOONHH......
    .....HHNGENNNEGNHH......
    ......HNENHHHNENH.......
    ........HHHHHHH.........
  `,
  sprite`
    ........................
    ........................
    .........NN.............
    ........NWSN............
    ......NNWWWSN...........
    ......NWNNOOONN.........
    .......NDOOYOODN........
    .....NNNNDOYODNNNN......
    .....NGGGNDODNGGGN......
    ......NWGDNNNDGWN.......
    ......NWOOOOOOOWN.......
    .......NOOOOOOON........
    .......NOBOYOBON........
    ......NWWBOYOBWWN.......
    ......HNNPWBWPNNH.......
    .....HNWSNNNNNSWNH......
    .....HHNOSSSSSONHH......
    .....HHNGENNNNENHH......
    ......HNENHHHHHHH.......
    ........HHHHHHH.........
  `,
];

const backFrames = [
  sprite`
    ........................
    ........................
    ........................
    .....NNNN.....NNNN......
    .....NGGGN...NGGGN......
    ......NGGDNNNDGGN.......
    ......NGOOYYYOOGN.......
    .......NOOOYOOON........
    .......NWOOOOOWN........
    ......NWWOOOOOWWN.......
    .......NNWOOOWNN........
    ........NNDDDNN.........
    ........NDDDDDN.........
    .......NDODODODN........
    ......HNOONONOONH.......
    .....HHNONOOONONHH......
    .....HHNONWWWNONHH......
    .....HHNGENNNEGNHH......
    ......HNENHHHNENH.......
    ........HHHHHHH.........
  `,
  sprite`
    ........................
    ........................
    ........................
    ........................
    .....NNNN.....NNNN......
    .....NGGGN...NGGGN......
    ......NGGDNNNDGGN.......
    ......NGOOYYYOOGN.......
    .......NOOOYOOON........
    .......NWOOOOOWN........
    ......NWWOOOOOWWN.......
    .......NNWOOOWNN........
    ........NNDDDNN.........
    ........NDDDDDN.........
    ......HNODNOONDNH.......
    .....HHNOONOOWNNHH......
    .....HHNGENNWWWNHH......
    .....HHNENHHNNNNHH......
    ......HHHHHHHNENH.......
    ........HHHHHHH.........
  `,
  sprite`
    ........................
    ........................
    ........................
    .....NNNN.....NNNN......
    .....NGGGN...NGGGN......
    ......NGGDNNNDGGN.......
    ......NGOOYYYOOGN.......
    .......NOOOYOOON........
    .......NWOOOOOWN........
    ......NWWOOOOOWWN.......
    .......NNWOOOWNN........
    ........NNDDDNN.........
    ........NDDDDDN.........
    .......NDODODODN........
    ......HNOONONOONH.......
    .....HHNONOOONONHH......
    .....HHNONWWWNONHH......
    .....HHNGENNNEGNHH......
    ......HNENHHHNENH.......
    ........HHHHHHH.........
  `,
  sprite`
    ........................
    ........................
    ........................
    ........................
    .....NNNN.....NNNN......
    .....NGGGN...NGGGN......
    ......NGGDNNNDGGN.......
    ......NGOOYYYOOGN.......
    .......NOOOYOOON........
    .......NWOOOOOWN........
    ......NWWOOOOOWWN.......
    .......NNWOOOWNN........
    ........NNDDDNN.........
    .......NNDDDDDNN........
    ......HNDNOONDONH.......
    .....HHNNWOONOONHH......
    .....HHNWWWNNEGNHH......
    .....HHNNNNHHNENHH......
    ......HNENHHHHHHH.......
    ........HHHHHHH.........
  `,
];

const frontFrames = [
  sprite`
    ........................
    ...........N............
    ..........NWN...........
    .........NWWSN..........
    ........NNOOONN.........
    .......NDOOYOODN........
    .....NNNNDOYODNNNN......
    .....NGGGNDODNGGGN......
    ......NWGDNNNDGWN.......
    ......NWOOOOOOOWN.......
    .......NOOOOOOON........
    .......NOBOYOBON........
    ......NWWBOYOBWWN.......
    .......NNPWBWPNN........
    ......NWSNNNNNSWN.......
    .....HHNOSSSSSONHH......
    .....HHNOOWWWOONHH......
    .....HHNGENNNEGNHH......
    ......HNENHHHNENH.......
    ........HHHHHHH.........
  `,
  sprite`
    ........................
    ........................
    ........................
    ........................
    .....NNNN.....NNNN......
    .....NGGGN...NGGGN......
    ......NWGDNNNDGWN.......
    ......NWOOOOOOOWN.......
    .......NOOOOOOON........
    .......NOBOYOBON........
    ......NWWBOYOBWWN.......
    .......NNPWBWPNN........
    ......NWSNNNNNSWN.......
    ......NOWSSSSSWON.......
    .....NDOOWWWWWOODN......
    .....NGNOOWWWOONGN......
    .....HNNDGNSNGDNNH......
    .....HHNGENNNEGNHH......
    ......HNENHHHNENH.......
    ........HHHHHHH.........
  `,
  sprite`
    ........................
    ........................
    ........................
    .....NNNN.....NNNN......
    .....NGGGN...NGGGN......
    ......NWGDNNNDGWN.......
    ......NWOOOOOOOWN.......
    .......NOOOOOOON........
    .......NOBOYOBON........
    ......NWWBOYOBWWN.......
    .......NNPWBWPNN........
    ......NWSNNNNNSWN.......
    .......NWSSSSSWN........
    .......NOWWWWWON........
    ......NDOOWWWOODN.......
    .....HNDNOOEOONDNH......
    .....HNGNDGNGDNGNH......
    .....HHNNGENEGNNHH......
    ......HHNENHNENHH.......
    ........HHHHHHH.........
  `,
  sprite`
    ........................
    ........................
    ........................
    .....NNNN.....NNNN......
    .....NGGGN...NGGGN......
    ......NWGDNNNDGWN.......
    ......NWOOOOOOOWN.......
    .......NOOOOOOON........
    .......NOBOYOBON........
    ......NWWBOYOBWWN.......
    .......NNPWBWPNN........
    ......NWSNNPNNSWN.......
    .......NWSSSSSWN........
    .......NOWWWWWON........
    ......NDOOWWWOODN.......
    .....HNDNOOEOONDNH......
    .....HNGNDGNGDNGNH......
    .....HHNNGENEGNNHH......
    ......HHNENHNENHH.......
    ........HHHHHHH.........
  `,
];

const sleepingFrames = [
  sprite`
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........NNNNNNN.........
    .......NDDDOOOONN.......
    ..NNNNNDDDNNNNNOYN......
    ..NGGGDNNNDGGGNOOYN.....
    ...NWOOOOOOOWNDDOON.....
    ....NOOOOOOONDDDNOON....
    ....NOOOYOOONDDNNOOON...
    ...NWWBBYBBWWNNSOOOWNQ..
    ....NNPWBWPNNSSWWWWWNQ..
    .....QNNNNNQNSSSSWSNQ...
    ......QQQQQQQNNNNNNQ....
  `,
  sprite`
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........NNNNNNNNN.......
    .......NDDDOOOOOON......
    ..NNNNNDDDNNNNNOOYN.....
    ..NGGGDNNNDGGGNOOOYN....
    ...NWOOOOOOOWNDDOOON....
    ....NOOOOOOONDDDNOON....
    ....NOOOYOOONDDNNOOON...
    ...NWWBBYBBWWNNSOOOWNQ..
    ....NNPWBWPNNSSWWWWWNQ..
    .....QNNNNNQNSSSSWSNQ...
    ......QQQQQQQNNNNNNQ....
  `,
  sprite`
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........NNNNNNN.........
    .......NDDDOOOONN.......
    ..NNNNNDDDNNNNNOYN......
    ..NGGGDNNNDGGGNOOYN.....
    ...NWOOOOOOOWNDDOON.....
    ....NOOOOOOONDDDNOON....
    ....NOOOYOOONDDNNOOON...
    ...NWWBBYBBWWNNSOOOWNQ..
    ....NNPWBWPNNSSWWWWWNQ..
    .....QNNNNNQNSSSSWSNQ...
    ......QQQQQQQNNNNNNQ....
  `,
  sprite`
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........NNNNNNNNN.......
    .......NDDDOOOOOON......
    ..NNNNNDDDNNNNNOOYN.....
    ..NGGGDNNNDGGGNOOOYN....
    ...NWOOOOOOOWNDDOOON....
    ....NOOOOOOONDDDNOON....
    ....NOOOYOOONDDNNOOON...
    ...NWWBBYBBWWNNSOOOWNQ..
    ....NNPWBWPNNSSWWWWWNQ..
    .....QNNNNNQNSSSSWSNQ...
    ......QQQQQQQNNNNNNQ....
  `,
];

type Pixel = readonly [x: number, y: number, color: string];

function setPixels(frame: string[], pixels: Pixel[]): string[] {
  const result = frame.map((row) => row.split(""));
  for (const [x, y, color] of pixels) {
    if (x >= 0 && x < FOX_WIDTH && y >= 0 && y < FOX_HEIGHT) {
      result[y][x] = color;
    }
  }
  return result.map((row) => row.join(""));
}

function removeColors(frame: string[], colors: Set<string>): string[] {
  return frame.map((row) =>
    [...row].map((pixel) => (colors.has(pixel) ? "." : pixel)).join(""),
  );
}

function shiftFrame(frame: string[], offsetY: number): string[] {
  const result = Array.from({ length: FOX_HEIGHT }, () =>
    ".".repeat(FOX_WIDTH),
  );
  for (let y = 0; y < FOX_HEIGHT; y += 1) {
    const destinationY = y + offsetY;
    if (destinationY >= 0 && destinationY < FOX_HEIGHT) {
      result[destinationY] = frame[y];
    }
  }
  return result;
}

const sniffFrames = sideFrames.map((frame, index) =>
  setPixels(frame, [
    [1 - (index % 2), 8 - Math.floor(index / 2), "G"],
    [index === 2 ? 0 : -1, 6, "S"],
  ]),
);

const digFrames = backFrames.map((frame, index) =>
  setPixels(frame, [
    [3 + index, 17 - (index % 2), index % 2 === 0 ? "F" : "D"],
    [20 - index, 18, index % 2 === 0 ? "D" : "F"],
    [index === 1 ? 2 : 21, 15 + (index % 2), "F"],
  ]),
);

const sideWithoutShadow = sideFrames.map((frame) =>
  removeColors(frame, new Set(["Q"])),
);

const runFrames = sideWithoutShadow.map((frame, index) =>
  setPixels(shiftFrame(frame, index % 2 === 0 ? 0 : -1), [
    [22 - index, 17 + (index % 2), "Q"],
    [20 - index, 19, "H"],
  ]),
);

const jumpOffsets = [0, -2, -4, -2];
const jumpFrames = sideWithoutShadow.map((frame, index) =>
  setPixels(shiftFrame(frame, jumpOffsets[index]), [
    [index < 2 ? 21 : 2, index === 2 ? 5 : 3 + index, "Y"],
    [index === 2 ? 22 : -1, 9, "Y"],
  ]),
);

const caughtFrames = frontBounceFrames.map((frame, index) =>
  setPixels(frame, [
    [index % 2 === 0 ? 3 : 20, 3 + (index % 2), "Y"],
    [index === 2 ? 21 : 2, 10, "Y"],
  ]),
);

const errorFrames = [
  setPixels(frontFrames[0], [
    [20, 1, "R"],
    [20, 2, "R"],
    [20, 4, "R"],
  ]),
  frontFrames[1],
  setPixels(frontFrames[2], [
    [20, 1, "R"],
    [20, 2, "R"],
    [20, 4, "R"],
  ]),
  frontFrames[3],
];

const sadFrames = [
  setPixels(frontFrames[2], [[9, 9, "C"]]),
  setPixels(frontFrames[3], [
    [9, 9, "C"],
    [14, 9, "C"],
  ]),
  setPixels(frontFrames[2], [
    [9, 10, "C"],
    [14, 10, "C"],
  ]),
  setPixels(frontFrames[3], [[14, 9, "C"]]),
];

export const ANIMS: Record<FoxState, FoxAnimation> = {
  sleep: {
    label: "esperando você…",
    intervalMs: 700,
    grids: sleepingFrames,
  },
  sniff: {
    label: "farejando o código",
    intervalMs: 280,
    grids: sniffFrames,
  },
  dig: {
    label: "cavando na base",
    intervalMs: 220,
    grids: digFrames,
  },
  run: {
    label: "correndo atrás",
    intervalMs: 130,
    grids: runFrames,
  },
  jump: {
    label: "pulando de alegria!",
    intervalMs: 160,
    grids: jumpFrames,
  },
  caught: {
    label: "pegou!",
    intervalMs: 170,
    once: { durationMs: 1600, then: "sleep" },
    grids: caughtFrames,
  },
  error: {
    label: "ai! deu erro",
    intervalMs: 190,
    once: { durationMs: 1200, then: "sleep" },
    grids: errorFrames,
  },
  sad: {
    label: "tá difícil hoje…",
    intervalMs: 580,
    grids: sadFrames,
  },
  swim: {
    label: "nadando no código",
    intervalMs: 200,
    grids: runFrames,
  },
};

export const FOX_STATES = Object.keys(ANIMS) as FoxState[];

const paletteKeys = new Set(Object.keys(PALETTE));

for (const [state, animation] of Object.entries(ANIMS)) {
  for (const [frameIndex, frame] of animation.grids.entries()) {
    if (frame.length !== FOX_HEIGHT) {
      throw new Error(
        `${state} frame ${frameIndex} has ${frame.length} rows; expected ${FOX_HEIGHT}`,
      );
    }
    for (const [rowIndex, row] of frame.entries()) {
      if (row.length !== FOX_WIDTH) {
        throw new Error(
          `${state} frame ${frameIndex} row ${rowIndex} has ${row.length} pixels; expected ${FOX_WIDTH}`,
        );
      }
      for (const pixel of row) {
        if (pixel !== "." && !paletteKeys.has(pixel)) {
          throw new Error(
            `${state} frame ${frameIndex} row ${rowIndex} uses unknown pixel ${pixel}`,
          );
        }
      }
    }
  }
}
